steps:
  # Build the application with Gradle
  - name: 'gradle:jdk21'
    entrypoint: 'gradle'
    args: ['build']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/form-management:latest', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/form-management:latest']

  # Deploy to Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'beta'
      - 'deploy'
      - 'releases'
      - 'create'
      - 'rel-${SHORT_SHA}'
      - '--delivery-pipeline'
      - 'form-management-pipeline'
      - '--region'
      - '${_REGION}'
      - '--annotations'
      - 'commitId=${COMMIT_SHA}'
      - '--source'
      - 'k8s/'

images:
  - 'gcr.io/${PROJECT_ID}/form-management:latest'

substitutions:
  _REGION: us-central1  # Replace with your region

options:
  logging: CLOUD_LOGGING_ONLY