apiVersion: v1
kind: Service
metadata:
  name: form-management
spec:
  selector:
    app: form-management
  ports:
    -port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form-management
  template:
    metadata:
      labels:
        app: form-management
    spec:
      containers:
        -name: form-management
        image: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/form-management/form-management:latest
        ports:
          - containerPort: 8080