apiVersion: skaffold/v3
kind: Config
metadata:
  name: form-management
build:
  artifacts:
      - image: REGION-docker.pkg.dev/PROJECT_ID/form-management/form-management
        context: ..
  googleCloudBuild:
    projectId: PROJECT_ID
manifests:
  rawYaml:
    - k8s/manifest.yaml
profiles:
  - name: main-cluster
    build:
      artifacts:
        - image: REGION-docker.pkg.dev/PROJECT_ID/form-management/form-management
          context: ..
    manifests:
      rawYaml:
        - k8s/manifest.yaml