apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: form-management
profiles:
  - name: main-cluster
    manifests:
      rawYaml:
        - k8s/deployment.yaml
        - k8s/service.yaml
build:
  artifacts:
    - image: REGION-docker.pkg.dev/PROJECT_ID/form-management/form-management
      docker:
        dockerfile: Dockerfile