apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: form-management
build:
  artifacts:
      - image: REGION-docker.pkg.dev/PROJECT_ID/form-management/form-management
        context: src
profiles:
  - name: main-cluster
    build:
      artifacts:
        - image: REGION-docker.pkg.dev/PROJECT_ID/form-management/form-management
          context: src
    deploy:
      kubectl: { }