apiVersion: skaffold/v3
kind: Config
metadata:
  name: form-management
build:
  artifacts:
      - image: REGION-docker.pkg.dev/PROJECT_ID/form-management/form-management
        context: src
manifests:
  rawYaml:
    - manifest.yml
profiles:
  - name: main-cluster
    build:
      artifacts:
        - image: REGION-docker.pkg.dev/PROJECT_ID/form-management/form-management
          context: src
    manifests:
      rawYaml:
        - manifest.yml