apiVersion: skaffold/v3
kind: Config
metadata:
  name: form-management
build:
  artifacts:
      - image: us-central1-docker.pkg.dev/ralphqa/form-management/form-management
        context: ..
  googleCloudBuild:
    projectId: ralphqa
manifests:
  rawYaml:
    - manifest.yaml
profiles:
  - name: main-cluster
    build:
      artifacts:
        - image: us-central1-docker.pkg.dev/ralphqa/form-management/form-management
          context: ..
    manifests:
      rawYaml:
        - manifest.yaml