apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: form-management
profiles:
  - name: main-cluster
    build:
      googleCloudBuild:
        projectId: PROJECT_ID
      artifacts:
        - image: REGION-docker.pkg.dev/PROJECT_ID/form-management/form-management
          docker:
            dockerfile: Dockerfile
    manifests:
      rawYaml:
        - k8s/deployment.yaml
        - k8s/service.yaml
    deploy:
      kubectl: { }