apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: form-management
profiles:
  - name: main-cluster
    deploy:
      kubectl:
        manifests:
          - k8s/deployment.yaml
          - k8s/service.yaml
build:
  artifacts:
    - image: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/form-management/form-management:latest
      docker:
        dockerfile: Dockerfile